### ISSUE TITLE
Re. the Thanks

### ISSUE THREAD

**Issue by dandv** [IonicaBizau/debug-mode#12]
Thanks for another cool module!

Re. the [Thanks](https://github.com/IonicaBizau/debug-mode#cake-thanks) section in the README - it may suggest that that answer is how the module works, but as pointed out, the answer no longer works for current versions of Node.

Might want to link to https://github.com/nodejs/node/issues/9617 ?

**Comment by IonicaBizau** [comment]
You're welcome! :)

> Might want to link to nodejs/node#9617 ?

Indeed! :+1: Thanks for pointing that out!
