### ISSUE TITLE
Not working from IDEs

### ISSUE THREAD

**Issue by dandv** [IonicaBizau/debug-mode#15]
I'm using node v13.11.0 with WebStorm EAP, and the module returns `false` even when it's being debugged:

![image](https://user-images.githubusercontent.com/33569/77918736-c4f3f680-72f8-11ea-8356-2262b089a2cf.png)

WebStorm used to pass the `--inspect` flag, but it no longer does that. Maybe it sends [`SIGUSR1`](https://nodejs.org/en/docs/guides/debugging-getting-started/)?

**Comment by IonicaBizau** [comment]
Can you please check if there are any debug processes visible in the output of `ps aux | grep node`?

Also, you can inspect the value of `process.execArgv` in the debugging context.
