### ISSUE TITLE
Hey, you're stealing my ideas! :D

### ISSUE THREAD

**Issue by oliversalzburg** [IonicaBizau/debug-mode#2]
https://github.com/oliversalzburg/debugger-attached is literally the exact same thing. Scary :D

**Comment by IonicaBizau** [comment]
😂

I did make a quick search to see any potential existing modules and didn't find them, so I just quickly created a new one.

This is different tho because it's an ES6 arrow function and has tests and documentation. 😁

**Comment by oliversalzburg** [comment]
Is that test working for you? I had trouble with testing because changes to `global` did not persist outside the test. I have a hard time reading the output of `tester` :\

**Comment by IonicaBizau** [comment]
> I have a hard time reading the output of `tester`

What do you mean?

Yes, the test is passing. It's basically just simulating the `v8debug` global object.

**Comment by oliversalzburg** [comment]
![image](https://cloud.githubusercontent.com/assets/1658949/19639685/bf4f8100-99d9-11e6-9b16-81a77e952031.png)

**Comment by oliversalzburg** [comment]
And for some reason I remembered something about every module having its own `global` and that it wasn't actually shared. But I must have confused that with something else. :\

**Comment by IonicaBizau** [comment]
We can set globals by appending things in the `global` object.

Oh, seems that it's broken on Windows, lol. 😂 Looks good on macOS and Linux.
